#!/usr/bin/env php
<?php declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

use PicqerExactPhpClientGenerator\Command\ModelGenerateCommand;
use Symfony\Component\Console\Application;

chdir(__DIR__);

$application = new Application();
$command = new ModelGenerateCommand();

$application->add($command);
$application->setDefaultCommand($command->getName(), true);

$application->run();