blank_issues_enabled: false
contact_links:
  - name: Piqcer Exact PHP Client Generator
    url: https://github.com/DannyvdSluijs/PicqerExactPhpClientGenerator/discussions
    about: Please ask and answer questions here.