name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: PHP 8.4 build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Setup PHP 8.4
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.4
        coverage: xdebug

    - name: Install dependencies
      run: composer install

    - name: Run unit tests
      run: composer unit-tests
